### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by mnpenner** [dylanblokhuis/kysely-bun-sqlite#3]
Hi,

I stumbled across your project when I read this:

![image](https://github.com/dylanblokhuis/kysely-bun-sqlite/assets/1112998/94343492-f380-4659-88a1-c8213515338f)

Looks like this project aims to fill that gap. Looks like it's still new -- does it work yet? Anything folks should know before using it?

Thanks for putting this online!

**Comment by dylanblokhuis** [comment]
Yes, it does work. I just added a simple example. https://github.com/dylanblokhuis/kysely-bun-sqlite/tree/master/examples/simple
